### DISCUSSION TITLE
"error": "--to is not a valid sha pointer: \"HEAD\", --from is not a valid sha pointer: \"origin/develop\""

### DISCUSSION THREAD

**Discussion by niv-goldenberg** [scolladon/sfdx-git-delta#387] [Show and tell]
I'm opening this issue with a solution for documentation as I just spent several hours to solve it.

I had the same issue as here: https://bytemeta.vip/repo/scolladon/sfdx-git-delta/issues/373

The owner of the issue has stopped using Docker image as a solution. I propose a different solution that allows you to keep using the docker image.

I recently updated my docker images, which include all sfdx and sfdx-git-delta to the latest versions. After the update I got the  following issue: 
```
{
  "error": "--to is not a valid sha pointer: \"HEAD\", --from is not a valid sha pointer: \"origin/develop\"",
  "output": ".",
  "success": false,
  "warnings": []
}
```

Long story short, trying to access the git logs (by using git log) directly gave the solution of just applying the checkout (v3) working folder as a safe directory (before running any sfdx-git-delta commands), for example in my case:
`git config --global --add safe.directory /__w/core-platform/core-platform`

Hope it will save time for someone else in the future.

**Comment by scolladon** [comment]
Hi @niv-goldenberg !

Thanks for the time you spent on it and for the solution!

Can you give a bit more detail please ?
For example can you give the github action yaml file ?

I think we could convert this into a discussion if you agree

**Comment by packocz** [comment]
I'd also be very interested in more detail for the solution. I tried to apply it like below, but it's not helped:

```
deploy-dev:
        runs-on: 'ubuntu-latest'
        container: salesforce/salesforcedx:latest-rc-full
        #concurrency: deploy-dev
        env:
            SFDX_DISABLE_DNS_CHECK: true
        steps:
            - name: Clone Repository (Latest)
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 

            - name: 'Populate auth file with secret'
              shell: bash
              run: ......

            - name: 'Authenticate Org'
              run: ....

            - name: 'Set safe folder'
              run: git config --global --add safe.directory /__w/core-platform/core-platform

            - name: 'Install SFDX Git Delta plugin'
              run: echo y | sfdx plugins:install sfdx-git-delta

            - name: 'Generate Delta manifest'
              run: sfdx sgd:source:delta --from "successful-dev-build" --to "$GITHUB_SHA" --output .
```
Same command locally runs fine, only GitHub Action has the problem
