### DISCUSSION TITLE
Caching Salesforce CLI & SFDX Git Delta

### DISCUSSION THREAD

**Discussion by jonny-harte** [scolladon/sfdx-git-delta#743] [Show and tell]
Here's how I was able to cache the Salesforce CLI & SFDX Git Delta. There's two steps to the process.

1. Save Cache - A manual workflow run to build the cache. This is performed on the main branch so all PR's can use the the same cache. To update simply delete the cache and re-run the flow.

2. Restore the cache before running sf cli commands.

Before implementing this it was taking 50+ seconds to install the cli and plugin per workflow run. That has been reduced down to 5-7 seconds.

```
name: Save Cache

on:
  workflow_dispatch:

jobs:
  SFDX-Git-Delta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20"

      - name: Add NPM Prefix to Environment
        shell: bash
        run: echo "NPM_PREFIX=$(npm config get prefix)" >> $GITHUB_ENV

      - name: Install Salesforce CLI & SFDX Git Delta
        run: |
          npm install @salesforce/cli --global --omit=dev
          echo y | sf plugins install sfdx-git-delta

      - name: Save Cache
        uses: actions/cache/save@v3
        with:
          path: |
            /home/runner/.local/share/sf
            ${{ env.NPM_PREFIX }}/bin
            ${{ env.NPM_PREFIX }}/lib/node_modules/@salesforce/cli
          key: SFDX-Git-Delta
```

```
name: Salesforce Deployment

on:
  workflow_call:

jobs:
  Salesforce-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20"

      - name: Add NPM Prefix to Environment
        shell: bash
        run: echo "NPM_PREFIX=$(npm config get prefix)" >> $GITHUB_ENV

      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /home/runner/.local/share/sf
            ${{ env.NPM_PREFIX }}/bin
            ${{ env.NPM_PREFIX }}/lib/node_modules/@salesforce/cli
          key: SFDX-Git-Delta
```
