### ISSUE TITLE
--from is not a valid sha pointer:

### ISSUE THREAD

**Issue by shreyagoyal06** [scolladon/sfdx-git-delta#1092]
Getting below error in the github pipeline
Failure: --from is not a valid sha pointer: 'origin/main' (If in CI/CD context, check the fetch depth is properly set), --to is not a valid sha pointer: 'HEAD' (If in CI/CD context, check the fetch depth is properly set)

Below is the yml being used

```yaml
name: Auto Validate and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: 
      image: salesforce/cli:latest-full
    steps:
      - name: Install sgd plugin
        run: |
         echo 'y' | sf plugins install sfdx-git-delta

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create delta package
        run: |
          sf sgd source delta --to HEAD --from origin/${{ github.event.pull_request.base.ref }} --output-dir .
```

**Comment by scolladon** [comment]
Hi @shreyagoyal06!

Thanks for raising this issue and thanks for contributing in making this project better!

Could you try without specifying "origin/" please ?

**Comment by shreyagoyal06** [comment]
Hi @scolladon 

Hope you are doing well!

I did try without specifying origin still the same issue
Failure: --from is not a valid sha pointer: 'main' (If in CI/CD context, check the fetch depth is properly set), --to is not a valid sha pointer: 'HEAD' (If in CI/CD context, check the fetch depth is properly set)

**Comment by scolladon** [comment]
From what I can see in the web, there could be an [issue with container and checkout](https://github.com/actions/checkout/issues/1487)...

Could you try without the container please ?
Something like that (I have not tested) : 
```yaml
name: Auto Validate and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Install sf cli
        run: npm install @salesforce/cli --global

      - name: Install sgd plugin
        run: echo 'y' | sf plugins install sfdx-git-delta

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create delta package
        run: |
          sf sgd source delta --to HEAD --from origin/${{ github.event.pull_request.base.ref }} --output-dir .
```
