### ISSUE TITLE
getting 'error sfdx-git-delta@6.15.0: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.15.0" error Found incompatible module.

### ISSUE THREAD

**Issue by sheidasf** [scolladon/sfdx-git-delta#1097]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

i get an issue this morning on installing the package
error sfdx-git-delta@6.15.0: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.15.0"
error Found incompatible module.

---

### What is the parameter and the value you used with it?

This i my install command:
 sfdx plugins:install -f sfdx-git-delta@stable

## Steps to reproduce

---

## Execution context

---

**Operating System:** …

**npm version:** …

**node version:** …

**git version:** …

**sf version:** …

**sgd plugin version:** …

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @sheidasf!

Thanks for raising this issue and thanks for contributing in making this project better!

Unfortunately this is not an issue.
The plugin is [no longer compatible with node 18](https://github.com/scolladon/sfdx-git-delta/issues/1081) (as the sf cli)

**Comment by sheidasf** [comment]
Thank you. i have to change the node to a higer version. Thakn you so much for the fast response. for now since i don't know where the node is coming , we went back to verison 6.14.0

**Comment by sheidasf** [comment]
In genral, how long do you keep old versions alive? thank you

**Comment by scolladon** [comment]
We follow sf cli which follows node itself

**Comment by a-barwick** [comment]
Did you consider making this a major version update instead of a minor one? Minor semver changes should avoid breaking changes like this one. One of our major CI/CD pipelines was blocked because of this change.

**Comment by scolladon** [comment]
Hi @a-barwick 

Nop we did not consider doing a major here. We followed sf cli.

Do you think it would have prevent you from encountering the issue in your pipeline ?

**Comment by BrettMN** [comment]
I am getting this error with my Github workflow.   The workflow is running Node `v24.3.0`

**Comment by scolladon** [comment]
> I am getting this error with my Github workflow.   The workflow is running Node `v24.3.0` 

How sf cli is installed in your pipeline ? 

Could you show the configuration ?

**Comment by BrettMN** [comment]
Here is our steps that lead up the the error. 


```yml

        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: '24'

            - name: Node.js version
              run: node -v
            - name: Deploy Started Notification
              uses: mikesprague/teams-incoming-webhook-action@v1
              with:
                  github-token: ${{ github.token }}
                  webhook-url: ${{ secrets.MS_TEAMS_SHARED_DEV_WEBHOOK_URI }}
                  deploy-card: true
                  title: 'Deployment Started'
                  color: 'info'

            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install Salesforce CLI
              run: >
                  wget
                  https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

                  mkdir ~/sfdx

                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1

                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH

                  ~/sfdx/bin/sfdx version
            - name: Populate auth file with SFDX_URL_SHARED_DEV secret of target org
              run: |
                  echo ${{ secrets.SFDX_URL_SHARED_DEV }} > ./SFDX_URL_SHARED_DEV.txt
            - name: Authenticate to target Org
              run: sfdx auth:sfdxurl:store -f ./SFDX_URL_SHARED_DEV.txt -s -a targetOrg
            - name: Installing sfdx git delta
              run: |
                  echo y | sf plugins:install sfdx-git-delta
                  sfdx plugins
            - name: Create delta packages for new, modified or deleted metadata
              run: >
                  mkdir release

                  sf sgd source delta --to "HEAD" --from "HEAD^" --output release/ --generate-delta --source src/ --ignore .forceignore
```
