### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype') - Azure job

### ISSUE THREAD

**Issue by JaniszewskiMarcin** [scolladon/sfdx-git-delta#326]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

Hello @mehdisfdc,
I have problem with TypeError issue but the command is running on Azure job where we install everything from scratch at every iteration of the job, so the plugin is reinstalling all the time and still getting this error TypeError: Cannot read properties of undefined (reading 'prototype') with the command sfdx sgd:source:delta. So the re-installation do not help us in this case :/ Is there any other fix? I also set the comment in latest typeError issue If you want you can close this one and reopen the old one.

### What is the parameter and the value you used with it?

sfdx sgd:source:delta --from origin/$target --output src_delta/ -d

$target is whole target branch name.

### What is the expected result?

Generate package

### What is the actual result?

Not working

## Steps to reproduce

---

## Execution context

---

**Operating System:** ubuntu-20.04 version: 20220807.1

**yarn version:** "^1.21.1"

**node version:** ">=16.0.0"

**git version:**  2.37.1

**sfdx version:** 7.160.0

**sgd plugin version:** 5.3.1

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @JaniszewskiMarcin !

Thanks for raising this issue ! I'm sure it will help everyone in your situation.

Could you send us the setup of your azure job please ?
I would like to have the ability to reproduce the issue on my own with your setup.

**Comment by JaniszewskiMarcin** [comment]
Hello @scolladon!

I have updated the description :)

**Comment by scolladon** [comment]
Hi @JaniszewskiMarcin !

Thanks for the context information.

Could you provide your pipeline definition (yaml file) please?
So I can try in Azure as well and reproduce the issue on my own.

**Comment by JaniszewskiMarcin** [comment]
The .yml file contains two steps one for script to install or required plugins and the second one for the deployment like this:
```
- task: PowerShell@2
  displayName: "Plugins install"
  inputs:
    filePath: "./filePath/plugins.ps1"
    workingDirectory: "Repo"

- task: PowerShell@2
  env:
    SYSTEM_ACCESSTOKEN: AZURE_TOKEN
  displayName: "Deployment"
  inputs:
    filePath: "./filePath/deployment.ps1"
    workingDirectory: "Repo"
```
The plugin.ps1 script contains foreach with scripts that have to be installed:
```
Write-Host "Running SFDX plugins installation"
ForEach ( $Plugin in $pkgConfig.plugins ) {
    Write-Host "Installing: $Plugin"
    Write-Output 'y' | sfdx plugins:install $Plugin
}
```
