### ISSUE TITLE
salesforce delta deployment CICD using azure devops yaml

### ISSUE THREAD

**Issue by bharuk** [scolladon/sfdx-git-delta#573]
### Is your proposal related to a problem?

---
Hi we are planning to salesforce delta using azure devops CICD i want help from yaml script to build salesforce delta deployment
 
```yaml
trigger: none

resources:
    webhooks:
    - webhook: testspa_new          ### Webhook alias
      connection: testspa_new
      filters:
        - path: pull_request.merged  
          value: true
        - path: pull_request.base.ref  
          value: "develop"


    repositories:
    - repository: Mytest  
      type: githubenterprise
      name: karu-bhar/Mytest
      ref: develop
      endpoint: myrepo1

      extends:
      template: keyfiles.yml

variables:
    - name: devops_dir
      value: "/home/vsts/work/1/scripts-deploy"  
    - name: global_dir
      value: "/home/vsts/work/1/s/Mytest"
    #- group: varhashicorp
    #- group: vargroup-sfdx
     
stages:
 - stage: UnlockedPackage_Creation
   jobs:
      - job: Build 
        timeoutInMinutes: 360
        pool:
         vmImage: ubuntu-latest
         
        steps:
        - checkout: self
          path: scripts-deploy
        - checkout: Mytest
        - task: PowerShell@2
          displayName: 'List files in Git Directory'
          inputs:
            targetType: 'inline'
            script: 'Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" -recurse'    
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              cd $(System.DefaultWorkingDirectory)/Mytest
            #cat /home/vsts/work/1/s/Mytest/describe.log
        - task: Bash@3
          displayName: 'Set git config email & name'
          inputs:
            targetType: 'inline'
            script: |
             git config --global user.email "kar.bhar@xx.com"
             git config --global user.name "kar-bhar"
        - task: UsePythonVersion@0
          inputs:
           versionSpec: '3.7'
        - script: |
           python -m pip install --upgrade pip
        - bash:
           #python --version 
           pip install wheel --upgrade
           pip install dohq-artifactory
           pip install hvac
           pip install -r /home/vsts/work/1/scripts-deploy/folder/requirements.txt --no-cache-dir
          # pip install -r /home/vsts/work/1/s/scripts-deploy/folder/requirements.txt  
           
        #- script: pip install -r requirements.txt
        #  displayName: 'Install requirements'
        - bash:
           npm install -g npm
          displayName: Install Latest version of npm  

             #INSTALL SFDX_CLI
        - bash: 
            npm install sfdx-cli --global
          displayName: Install SFDX
           echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
        
        #INSTALL VLOCITY BUILD TOOL
        - bash:
            npm install --global vlocity
          displayName: Install Vlocity
        - bash: |
                 cd $(devops_dir)
                 sfdx force:auth:jwt:grant --clientid "3MVG" --jwtkeyfile "./buildfiles/server.key" --username "bharu@vois.sandbox" --instanceurl "https://login.salesforce.com"
        
        - task: Bash@3
          inputs:
           targetType: 'inline'
           script: |
            $logFile= sfdx force:mdapi:describemetadata -u "@vois.sandbox" -f $global_dir/describe.log --apiversion "56.0"`
````

### Describe a solution you propose

---

### Describe alternatives you've considered

---

### Additional context

---

**Comment by scolladon** [comment]
Hi,

I'm not very skilled at azure devops pipeline, but I'll ask experts around me and try to come with more precise advice.

The [guidelines](https://github.com/scolladon/sfdx-git-delta#cicd-specificity) when using SGD is to git fetch locally in the CI the references you are going to compare so SGD can access those.

So the checkout step should set `fetchDepth: 0`.

And then you can use SGD:
```yaml
- bash:
			mkdir output
            sfdx sgd:source:delta --to "HEAD" --from "<target-branch>" --output output -d
```

Then you can use the generated package.xml in `output/package/package.xml` to deploy or the source folder generated in the ` output`

Hope it helps

**Comment by bharuk** [comment]
I am getting error destructive changes should i create a directory in salesforce code repository?
Warning: We plan to deprecate this command in the future. Try using the "project deploy start" command instead.
Warning: The "--targetusername" flag has been deprecated. Use "--target-org | -o" instead.
Error (1): Deploy directory destructive does not exist or is not a directory
/home/vsts/work/_temp/cd3913f9-c8a4-405b-afdf-a1cf72dda31a.sh: line 2: unexpected EOF while looking for matching ``'
/home/vsts/work/_temp/cd3913f9-c8a4-405b-afdf-a1cf72dda31a.sh: line 3: syntax error: unexpected end of file
##[debug]Exit code 2 received from tool '/usr/bin/bash'

**Comment by scolladon** [comment]
The sample uses a `destructive` folder.
In this case it should be the `<output>/destructiveChanges`, where `output` is the folder passed to `--output / -o` parameter of the `sgd` command.

```yaml
jobs:
  - deployment: DeployPackage
    environment: ${{ parameters.environment }}
    container: salesforce/salesforcedx:latest-full
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            fetchDepth: 0
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: drop
              path: '$(Pipeline.Workspace)'
          - task: DownloadSecureFile@1
            name: jwtkeyfile
            displayName: 'Download JWT key file'
            inputs:
              secureFile: 'JWT-${{ parameters.library }}'
          - script: |
              echo y | sfdx plugins:install sfdx-git-delta
              sfdx plugins
            displayName: 'Installing SGD'
          - script: |
              sfdx force:auth:jwt:grant --clientid $(consumerkey) \
              --jwtkeyfile $(jwtkeyfile.secureFilePath) --username $(username) \
              --setalias ${{ parameters.library }} -r ${{ parameters.instanceurl }}
              sfdx force:auth:list
            displayName: 'Authenticate'
		 -script: |
			 mkdir output
              sfdx sgd:source:delta --to "HEAD" --from "<target-branch>" --output output -d
            displayName: 'Generate incremental package'
          - script: |
              sfdx force:source:deploy -p force-app -w 60 --targetusername $(username) --noprompt       
            displayName: 'Deploy package'
          # Following Script will remove Salesforce components specified in the destructive/destructiveChangesPost.xml file in target Orgs.
          - script: |
              sfdx force:mdapi:deploy -d output/destructiveChanges -w -1 --targetusername $(username) --ignorewarnings
            displayName: 'Destructive Changes'`
```

You need to replace target branch with the name of the branch the pull request is targetting, with its remote name.
Per example if your branch target the `main` branch and the remote is named `origin`, the target branch is `origin/main`
