### ISSUE TITLE
Fatal Error - Not a valid object name

### ISSUE THREAD

**Issue by mhousaini-aware** [scolladon/sfdx-git-delta#671]
## Error

Hey there, I'm receiving this error when executing the command in an Azure DevOps pipeline YAML script: `fatal: Not a valid object name HEAD^\n`

![image](https://github.com/scolladon/sfdx-git-delta/assets/85270714/0b66f747-a54b-4f60-9096-7e38f6249776)

## My Setup

- Ubuntu 22.04 virtual machine (agent)
- Bash 3.225.1
- Node.js v18.17.0 x64 (Active LTS version)
- Latest version of Salesforce CLI
- SFDX-Git-Delta v5.24.2
- Pipeline configured with YAML script - these are the CLI installation and SFDX-Git-Delta lines in the script:

```
- bash: 
    npm install @salesforce/cli --global
  displayName: Install Salesforce CLI

# echo 'y' ignores the digital signature warning
- bash: 
    echo 'y' | sf plugins install sfdx-git-delta 
  displayName: Install SFDX-Git-Delta

- bash: 
    sfdx sgd:source:delta --to HEAD --from HEAD^ --output deploy/ --source force-app/main/default --ignore .forceignore
  displayName: Generate Delta Changes
```

## Things I've Tried

- `--from "HEAD^"`
- `--from "HEAD~1"`
- `--from HEAD^`
- `--from origin/prjdev`
- `sfdx sgd:source:delta ...` 
- `sf sgd source delta ...` 

I receive the same error every single time (`\n` added to the end of whatever I specify for the `--from` option).

Any assistance would be much appreciated.
