### ISSUE TITLE
Where are the plugin files saved?

### ISSUE THREAD

**Issue by jonny-harte** [scolladon/sfdx-git-delta#742]
Where are the plugin files saved? I'm trying to Cache the CLI and plugin in a Github Action and have managed to cache the CLI but it's saying it can't find the plugin?

```
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20"

      - name: Install Salesforce CLI & SFDX Git Delta
        run: |
          npm install @salesforce/cli --global
          echo y | sf plugins install sfdx-git-delta

      - name: Save Cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.npm
            /opt/hostedtoolcache/node/20.10.0/x64/bin
            /opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/@salesforce/cli
          key: SFDX-Git-Delta
```
