### ISSUE TITLE
How to run Specified test class in bitbucket pipeline

### ISSUE THREAD

**Issue by shreyagoyal06** [scolladon/sfdx-git-delta#902]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
How do I run only specified test classes while deploying to SF environment?

  Its mentioned in the doc to use the 'xq' command but when I'm trying to install yq its installs correctly and shows the yq version as well after it when running the xq command provided in the documentation it shows "command not found"

below is the sample yml

```yaml
image: salesforce/cli:latest-full

pipelines:
  pull-requests:
    feature/*:
      - stage:
          name: Build and validate
          steps:
          - step:
              name: 'Install delta plugin and Create delta package'
              script:
                - echo "y" | sfdx plugins:install sfdx-git-delta
                - sfdx plugins
                - TARGET_BRANCH_COMMIT=$(git ls-remote origin refs/heads/$BITBUCKET_PR_DESTINATION_BRANCH | awk '{print $1}')
                - sfdx sgd:source:delta --to "HEAD" --from $TARGET_BRANCH_COMMIT --output .
                - echo "Installing yq"
                - apt-get update && apt-get install -y wget
                - wget https://github.com/mikefarah/yq/releases/download/v4.18.1/yq_linux_amd64 -O /usr/bin/yq
                - chmod +x /usr/bin/yq
                - yq --version
                - xq --version
                - xq . < package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | join(",")' > testclass.txt
                - cat testclass.txt
                - cat package/package.xml
                - cat destructiveChanges/destructiveChanges.xml
```

  Provide the command and the parameters you used
  Provided the yml above

### What is the expected result?
  to get test class names in testclass.txt file

### What is the actual result?
  xq:command not found
